### ISSUE TITLE
Cannot create bundles

### ISSUE THREAD

**Issue by Chris-Wimtech** [Androxyde/devices#88]
It's currently impossible to create a bundle because the "device" input is disable.

![](https://i.imgur.com/8Q9rmYl.png)

**Comment by ch3mn3y** [comment]
Double click the Device field and it will open new window with list of devices to choose. Double click the device name to get a list of variants to choose from. Doudlbe click the variant so it will be shown at the Device field.
[image](https://user-images.githubusercontent.com/20260224/52790153-2231d780-3066-11e9-9957-a645db177300.png)

**Comment by Chris-Wimtech** [comment]
oooh.... Now I feel stupid.

Why does it look like a text field if it's not, though?

**Comment by ch3mn3y** [comment]
Dunno. In the past (0.9.13.0, not sure about newer) it was a text field, so probably it was left as that and changed into some kind of "invisible" button.
